grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 3
model_selection:
  module_0:
    class: LogisticRegression
    module: sklearn.linear_model
    params:
      penalty: elasticnet
      solver: saga
    search_param_grid:
      penalty:
      - none
      - l2
      solver:
      - lbfgs
      - newton-cg
      - saga

    
  